version: '3.2'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=hitech_apd
      - POSTGRES_PASSWORD=cms
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    expose:
      - 5432
    ports:
      - 54325:5432

  mongo:
    image: mongo:4
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - DB_USER=mongodb
      - DB_PASSWORD=cms
      - DB_NAME=eapd
    volumes:
      - ./mongodata/database:/data/db
      - ./api/db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - 27017:27017
    restart: unless-stopped

  web:
    build: ./web
    image: cms-eapd/web
    environment:
      - API_URL=http://localhost:8081
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
    volumes:
      - type: bind
        source: ./web
        target: /app
        consistency: delegated
      - /app/node_modules
    ports:
      - 8080:8001

  api:
    build: ./api
    image: cms-eapd/api
    depends_on:
      - db
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:cms@db/hitech_apd
      - MONGO_URL=mongodb://mongodb:cms@mongo:27017/eapd
      - NODE_ENV=development
      - DISABLE_SAME_SITE=yes
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_API_KEY=${OKTA_API_KEY}
    volumes:
      - type: bind
        source: ./api
        target: /app
        consistency: delegated
      - /app/node_modules
    ports:
      - 8081:8000
      - 9229:9229

volumes:
  pgdata:
  mongodata:
